### ISSUE TITLE
CAP Crash

### ISSUE THREAD

**Issue by FalcoGer** [rosedu/Pidgin#3]
CAP causes pidgin to crash seemingly at random. I'm running ubuntu 18.04, pidgin version from the repositories 2.12.0. The crash is rare and seemingly at random. Here is the backtrace.

```
2270	././libpurple/account.c: No such file or directory.

Thread 1 "pidgin" received signal SIGSEGV, Segmentation fault.
purple_account_get_protocol_id (account=0x21) at ././libpurple/account.c:2270
(gdb) bt full
#0  0x00007ffff51d9f85 in purple_account_get_protocol_id (account=0x21)
    at ././libpurple/account.c:2270
#1  0x00007fffe677c385 in insert_cap_failure (stats=stats@entry=0x55555dd438d0)
    at ././pidgin/plugins/cap/cap.c:320
        buddy_name = 0x0
        protocol_id = <optimized out>
        account_id = <optimized out>
        status_id = <optimized out>
        current_time = <optimized out>
        minute = <optimized out>
#2  0x00007fffe677c6b1 in max_message_difference_cb (data=0x55555dd438d0)
    at ././pidgin/plugins/cap/cap.c:339
        stats = 0x55555dd438d0
#3  0x00007ffff551ec03 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#4  0x00007ffff551e185 in g_main_context_dispatch ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#5  0x00007ffff551e550 in  () at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#6  0x00007ffff551e862 in g_main_loop_run ()
    at /usr/lib/x86_64-linux-gnu/libglib-2.0.so.0
#7  0x00007ffff67d4a37 in gtk_main ()
    at /usr/lib/x86_64-linux-gnu/libgtk-x11-2.0.so.0
#8  0x000055555558f8a3 in main (argc=<optimized out>, argv=<optimized out>)
    at ././pidgin/gtkmain.c:938
        opt_force_online = 0
        opt_help = <optimized out>
        opt_login = 0
        opt_nologin = 0
        opt_version = <optimized out>
        opt_si = <optimized out>
        opt_config_dir_arg = <optimized out>
        opt_login_arg = <optimized out>
        opt_session_arg = <optimized out>
        search_path = <optimized out>
        accounts = <optimized out>
        sig_indx = 1
        sigset = {__val = {90118, 0 <repeats 15 times>}}
        errmsg = '\000' <repeats 601 times>...
        signal_channel = <optimized out>
        signal_status = <optimized out>
        signal_channel_watcher = 1
        segfault_message_tmp = <optimized out>
        error = 0x0
        opt = <optimized out>
        gui_check = <optimized out>
        debug_enabled = <optimized out>
        migration_failed = 0
        active_accounts = <optimized out>
        long_options = 
            {{name = 0x55555562c851 "config", has_arg = 1, flag = 0x0, val = 99}, {name = 0x55555561ab79 "debug", has_arg = 0, flag = 0x0, val = 100}, {name = 0x5555556287e2 "force-online", has_arg = 0, flag = 0x0, val = 102}, {name = 0x55555561c69b "help", has_arg = 0, flag = 0x0, val = 104}, {name = 0x55555562868e "login", has_arg = 2, flag = 0x0, val = 108}, {name = 0x5555556287ef "multiple", has_arg = 0, flag = 0x0, val = 109}, {name = 0x5555556287f8 "nologin", has_arg = 0, flag = 0x0, val = 110}, {name = 0x55555562c847 "session", has_arg = 1, flag = 0x0, val = 115}, {name = 0x55555561eebd "version", has_arg = 0, flag = 0x0, val = 118}, {name = 0x55555562c85a "display", has_arg = 1, flag = 0x0, val = 68}, {name = 0x55555562931a "sync", has_arg = 0, flag = 0x0, val = 83}, {name = 0x0, has_arg = 0, flag = 0x0, val = 0}}

```

**Comment by mihaimaruseac** [comment]
Hi. This is not the official Pidgin repository, instead it was a fork we used many years ago for a course
